name: hardermc-plugin
main: com.hardermc.HarderMC
version: 0.8.0
api-version: 1.15
commands:
  nextbm:
    description: Get the time until the next Blood Moon.
    usage: /nextbm
  bdloc:
    description: Get the location of the Boss Dungeon.
    usage: /bdloc
  level:
    description: Get the current level of the server.
    usage: /level
